server:
  port: 9090
  servlet:   context-path: /ies
   
#Pracle
#spring:
#  datasource:
#    password: Hitesh
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: Hitesh
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#mysql
#spring:
#  datasource:
#    password: root
#    url: jdbc:mysql://localhost:3306/ies
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#h2
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    password: hitesh121pawar121
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: hitesh121pawar@gmail.com